package com.dugcanlift.coach.data

import com.dugcanlift.coach.ui.parseExercises
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Run against the **shipped asset**, not a fixture. The library's whole value
 * is that every version reads one file, so a test over a hand-written sample
 * would pass on a file this app doesn't have.
 *
 * `browser-parity.json` is the same fixture LIFT Android pins itself to, byte
 * for byte, generated by running the browser's own picker logic over the same
 * asset (see `parity.mjs` beside it). This app and LIFT hold near-copies of
 * the parser and the title-casing; pinning both to one fixture is what turns a
 * divergence between them into a failing build rather than two apps that
 * quietly disagree about what a lift is called.
 */
class ExerciseLibraryTest {

    private val library: List<LibraryExercise> by lazy {
        parseExerciseLibrary(File("src/main/assets/$EXERCISE_LIBRARY_ASSET").readText())
    }

    private val browser: JSONObject by lazy {
        JSONObject(File("src/test/fixtures/browser-parity.json").readText())
    }

    private fun expected(key: String): List<String> {
        val array = browser.getJSONArray(key)
        return (0 until array.length()).map { array.getString(it) }
    }

    private fun actual(query: String, equipment: String = "") =
        searchExerciseLibrary(library, query, equipment).map { it.name }

    // MARK: - The bundled file

    @Test fun `the asset is present and holds all 873 exercises`() {
        assertEquals(873, library.size)
    }

    @Test fun `the same file parses to the same count the browser sees`() {
        assertEquals(browser.getInt("count"), library.size)
    }

    @Test fun `every row resolves its indices to a real muscle`() {
        val nameless = library.filter { it.muscle.isBlank() }
        assertTrue("rows with no muscle: ${nameless.take(3).map { it.name }}", nameless.isEmpty())
    }

    @Test fun `the first row matches the file`() {
        val first = library.first()
        assertEquals("3/4 Sit-Up", first.name)
        assertEquals("abdominals", first.muscle)
        assertEquals("body only", first.equipment)
    }

    @Test fun `a malformed row costs that row, not the library`() {
        val json = """
            {"muscles":["chest"],"equipment":["barbell"],"categories":["strength"],
             "levels":["beginner"],
             "exercises":[["Bench Press",0,0,0,0],["Nameless",9,9,9,9],["",0,0,0,0]]}
        """.trimIndent()
        val parsed = parseExerciseLibrary(json)

        assertEquals("the blank-named row is dropped, the other two are kept", 2, parsed.size)
        assertEquals("an out-of-range index is empty, not a crash", "", parsed[1].muscle)
    }

    // MARK: - Parity with the browser, and so with LIFT Android

    @Test fun `a name search returns the browser's rows in the browser's order`() {
        assertEquals(expected("bench"), actual("bench press"))
    }

    @Test fun `a muscle search matches the browser`() {
        assertEquals(expected("hamstrings"), actual("hamstrings"))
    }

    @Test fun `a filtered search matches the browser`() {
        assertEquals(expected("pressDumbbell"), actual("press", "dumbbell"))
    }

    @Test fun `an empty query matches the browser, cap included`() {
        assertEquals(expected("empty"), actual(""))
    }

    @Test fun `a search that fills the cap matches the browser`() {
        assertEquals(expected("squat"), actual("squat"))
    }

    @Test fun `every equipment value title cases the way the browser's regex does`() {
        val expected = browser.getJSONObject("equipTitleCase")
        expected.keys().forEach { raw ->
            assertEquals("titleCase('$raw')", expected.getString(raw), titleCaseAscii(raw))
        }
    }

    @Test fun `a hyphen starts a word, as it does in the browser's regex`() {
        assertEquals("E-Z Curl Bar", titleCaseAscii("e-z curl bar"))
    }

    @Test fun `search ignores case and surrounding space`() {
        assertEquals(actual("squat"), actual("  SQUAT  "))
    }

    @Test fun `a query nothing matches returns nothing`() {
        assertTrue(searchExerciseLibrary(library, "zzzznotalift").isEmpty())
    }

    @Test fun `every equipment filter chip matches something`() {
        EQUIPMENT_FILTERS.forEach { filter ->
            assertFalse(
                "no exercise uses equipment '$filter'",
                searchExerciseLibrary(library, query = "", equipmentFilter = filter).isEmpty()
            )
        }
    }

    // MARK: - What gets written into a routine

    @Test fun `a picked exercise becomes a line the routine parser understands`() {
        val squat = library.first { it.name == "Barbell Squat" }
        assertEquals("Barbell Squat | Barbell", squat.routineLine)

        val parsed = parseExercises(squat.routineLine)
        assertEquals(1, parsed.size)
        assertEquals("Barbell Squat", parsed[0].name)
        assertEquals("Barbell", parsed[0].equipment)
        assertTrue("the library knows the movement, not the prescription",
                   parsed[0].sets.isEmpty())
    }

    @Test fun `an exercise needing no equipment writes no pipe`() {
        val bodyweight = library.first { it.equipment.isBlank() }
        assertEquals(bodyweight.name, bodyweight.routineLine)
        assertEquals(bodyweight.name, parseExercises(bodyweight.routineLine)[0].name)
        assertEquals("", parseExercises(bodyweight.routineLine)[0].equipment)
    }

    @Test fun `a name containing a pipe would break the line grammar`() {
        // None do today. If the reference data ever gains one, the routine
        // editor silently splits the name at it, so fail here instead.
        assertTrue(
            "these names go into a pipe-delimited line: ${library.filter { "|" in it.name }.map { it.name }}",
            library.none { "|" in it.name }
        )
    }

    @Test fun `every exercise in the file survives the round trip into a routine`() {
        // The line grammar is the narrow point between the library and a
        // prescription, and it is stringly typed. Prove all 873 get through it
        // with their name and equipment intact rather than trusting a sample.
        library.forEach { exercise ->
            val parsed = parseExercises(exercise.routineLine)
            assertEquals("${exercise.name} produced ${parsed.size} lines", 1, parsed.size)
            assertEquals(exercise.name, parsed[0].name)
            assertEquals(exercise.storedEquipment, parsed[0].equipment)
        }
    }

    @Test fun `a picked line agrees with what LIFT Android would store`() {
        // LIFT builds its logged exercise from the same two fields. If these
        // two ever disagree, a prescription and the set logged against it stop
        // being the same lift, which is the bug the shared file prevents.
        val hit = library.first { it.name == "Barbell Bench Press - Medium Grip" }
        assertEquals("Barbell", hit.storedEquipment)
        assertEquals("chest, barbell", hit.detailLabel)
    }
}
